export const GET_MOVIE = 'GET_MOVIE';
export const GET_NUMBER_RESULTS_MOVIE = 'GET_NUMBER_RESULTS_MOVIE'
export const CLEAR = 'CLEAR';

export const GET_HISTORY = 'GET_HISTORY';

export const GET_SERIE = 'GET_SERIE';
export const GET_NUMBER_RESULTS_SERIE = 'GET_NUMBER_RESULTS_SERIE'
export const CLEAR_SERIE = 'CLEAR_SERIE'

export const GET_NUMBER_RESULTS_PEOPLE = 'GET_NUMBER_RESULTS_PEOPLE';
export const GET_PEOPLE = 'GET_PEOPLE';
export const CLEAR_PEOPLE = 'CLEAR_PEOPLE'

export const ADD_FAVORITE = 'ADD_FAVORITE'





