export const GET_MOVIE = 'GET_MOVIE';
export const GET_SERIE = 'GET_SERIE';


export const GET_NUMBER_RESULTS_MOVIE = 'GET_NUMBER_RESULTS_MOVIE'
export const GET_NUMBER_RESULTS_SERIE = 'GET_NUMBER_RESULTS_SERIE'

export const CLEAR = 'CLEAR';
export const GET_NUMBER_RESULTS = 'GET_NUMBER_RESULTS';
export const GET_NAME = 'GET_NAME';
export const CLEAR_SERIE = 'CLEAR_SERIE'